LAB_09/LAB_07/Components/NavMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LAB_07.Models;

namespace LAB_07.Components
{
    public class NavMenuViewComponent : ViewComponent
    {

        private IMovieRepository movieRepository;
        public NavMenuViewComponent(IMovieRepository movieRepository)
        {
            this.movieRepository = movieRepository;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData?.Values["Genre"];
            IEnumerable<string> genres = movieRepository.Movies
                .Select(m => m.Genre)
                .Distinct()
                .OrderBy(g => g);
            return View(genres);
        }
    }
}

LAB_09/LAB_07/Components/PlayListSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LAB_07.Models;
using Microsoft.AspNetCore.Mvc;

namespace LAB_07.Components
{
    public class PlayListSummaryViewComponent : ViewComponent
    {
        private PlayList playList;

        public PlayListSummaryViewComponent(PlayList playList)
        {
            this.playList = playList;
        }

        public IViewComponentResult Invoke()
        {
            return View(playList);
        }
    }
}

LAB_09/LAB_07/Controllers/StudioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LAB_07.Models;

namespace LAB_07.Controllers
{
    
    public class StudioController : Controller
    {
        private IStudioRepository studioRepository;
       

        public StudioController(IStudioRepository studioRepository)
        {
            this.studioRepository = studioRepository;
        }
        public IActionResult List() => View(studioRepository.Studios);
    }
}

LAB_09/LAB_07/Views/Shared/NavPartial.cshtml
<div class="navbar" role="navigation">
    <a class="navbar-brand" href="Studio/List">Studios</a>
    @*<a class="navbar-brand"  asp-controller="Studio" asp-action="List">Studios</a>*@

</div>

LAB_09/LAB_07/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Movies2</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body>
    @Html.Partial("NavPartial")
    <div class="pull-right">
        @await Component.InvokeAsync("PlayListSummary") 
    </div>
    <div class="row-panel">
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("NavMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>