LAB_11/LAB_07/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LAB_07.Models
{
    public class Movie
    {
        public int MovieID { get; set; }
        [Required(ErrorMessage ="Must enter a title")]
        public string MovieName { get; set; }
        
        [Required(ErrorMessage = "Must enter a genre")]
        public string Genre { get; set; }

        [Required][Range(0.01, int.MaxValue ,ErrorMessage = "Must enter a positive value")]
        public int Runtime { get; set; }

        [Required(ErrorMessage = "Must enter a date")]
        public DateTime? Release { get; set; }

        //Relationships
        public int StudioID { get; set; }
        public Studio Studio { get; set; }

        
        public List<MovieDirector> MovieDirectors { get; set; }
    }
}

LAB_11/LAB_07/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LAB_07.Models;
using LAB_07.Models.ViewModels;
namespace LAB_07.Controllers
{
    public class MovieController : Controller
    {
        private IMovieRepository movieRepository;
        private int pageSize = 4;
        public MovieController(IMovieRepository movieRepository)
        {
            this.movieRepository = movieRepository;
        }
        public IActionResult List(string genre, int page = 1)
        {
            IEnumerable<Movie> cMovie = movieRepository.Movies
            .Where(m => genre == null || m.Genre == genre)
            .OrderBy(m => m.MovieName)
            .Skip((page - 1) * pageSize)
            .Take(pageSize);


            PagingViewModel pagingViewModel = new PagingViewModel()
            {
                CurrentPage = page,
                RecordsPerPage = pageSize,
                TotalRecords = genre == null ?
                movieRepository.Movies.Count() :
                movieRepository.Movies.Where(m => m.Genre == genre).Count()

            };

            MovieListViewModel viewModel = new MovieListViewModel()
            {
                Movies = cMovie,
                PagingViewModel = pagingViewModel,
                CurrentGenre = genre
                
            };

             return View(viewModel);
        }
        //public IActionResult List() => View(movieRepository.Movies);

    }
}

LAB_11/LAB_07/Controllers/PlayListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LAB_07.Models;
using LAB_07.Models.ViewModels;
using LAB_07.Infrastructure;


namespace LAB_07.Controllers
{
    public class PlayListController : Controller
    {
        private IMovieRepository movieRepository;
        private PlayList playList;

        public PlayListController(IMovieRepository movieRepository, PlayList playListService)
        {
            this.movieRepository = movieRepository;
            playList = playListService;
                 
        }

        public RedirectToActionResult AddToPlayList(int movieId, string returnURL)
        {
            Movie movie = movieRepository.Movies.FirstOrDefault(m => m.MovieID == movieId);
            if(movie != null)
            {
                
                playList.AddMovie(movie);
                
            }
            return RedirectToAction("Index", new { returnURL });
        }

        public RedirectToActionResult RemoveFromPlayList(int movieId, string returnURL)
        {
            Movie movie = movieRepository.Movies.FirstOrDefault(m => m.MovieID == movieId);
            if (movie != null)
            {
               
                playList.RemoveMovie(movie);
               
            }
            return RedirectToAction("Index", new { returnURL });
        } 

        public IActionResult Index(string returnURL)
        {
            PlayListIndexViewmodel model = new PlayListIndexViewmodel()
            {
                PlayList = playList,
                ReturnUrl = returnURL
            };
            return View(model);
        }
        
        
    }
}

LAB_11/LAB_07/Views/Movie/List.cshtml
@model MovieListViewModel

<div class="panel-body">
    <h1>Movies</h1>

    <!-- <table class="table table-striped table-bordered">
         <tr>
             <th>Title</th>
             <th>Genre</th>
             <th>Length</th>
             <th>Release</th>


         </tr>
         @foreach (Movie m in Model.Movies)
         {

     <tr>
         <td>@m.MovieName</td>
         <td>@m.Genre</td>
         <td>@m.Runtime Minutes</td>
         <td>@m.Release</td>




     </tr>

         }
     </table>
        -->
    @foreach (Movie m in Model.Movies)
    {
        @Html.Partial("MoviePartial", m)
    }

    </div>
<div page-model="@Model.PagingViewModel" page-action="List"
     page-classes-enabled="true" page-class="btn" page-class-normal="btn-default"
     page-class-selected="btn-primary" class="btn-group pull-right"></div>

LAB_11/LAB_07/Views/Movie/MoviePartial.cshtml
@model Movie

<div class="well">
    <h3>
        <strong>@Model.MovieName</strong>
        <span class="pull-right label label-primary">
            
            @Model.Runtime Minutes
        </span>
    </h3>
    <form id="@Model.MovieID" asp-action="AddToPlayList" asp-controller="PlayList" method="post">
        <input type="hidden" asp-for="MovieID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="lead">
           
                @Model.Genre
               
            
            <button type="submit" class="btn btn-success btn-sm pull-right">
                Add To PlayList
            </button>
        </span>
    </form>
</div>